### ISSUE TITLE
Get together as a team

### ISSUE THREAD

**Issue by jbwoo9779** [StanfordCS194/Team-5#1]
Hi folks,

Please arrange to meet one another, find a good SGM time that works for you and get after the [Startup Your Team](https://github.com/StanfordCS194/Home/blob/master/Startup-Your-Team.md) assignment

Jeff

**Comment by icelandman2** [comment]
Hey everyone! My name is Matt Linker - nice to meet you guys!

We should try to get moving on this as soon as we can. I'm off-campus till very late Sunday night. We should probably meet Monday - would 4:30PM (usual class meeting time) work for everyone? What location works best for folks? I figure we can knock out most of the team startup assignment working together in an hour or so.

As for our Wednesday meeting - I'd prefer 4:20 or 4:40PM - do either of those work for everyone?

Finally, my number is 206-383-5537 - feel free to drop your numbers and I'll create a group chat!

**Comment by narcomey** [comment]
Hello Matt and all! Thanks for the initial message. I'm Andrew Narcomey. I'm also very busy this weekend until Sunday afternoon bc of a conference, so would be happy with Monday meeting. 4:30 pm or later would work for me. I am at Lag but don't mind meeting wherever people think is best. Regarding Wed meeting, I'd prefer 4:40 or later since I have class right before until 4:20. My number is 415-300-7144.

**Comment by swetharevanur** [comment]
Hi everyone! I'm Swetha Revanur - excited to work with you all! A Monday meeting at 4:30pm works just fine for me. I live on east campus, so maybe we can meet somewhere in the middle like Lathrop or OU. For Wednesday SGM, 4:20 and 4:40 work best for me. 

My number is 408-666-4936, and you can also reach me on Facebook Messenger!

**Comment by tina98** [comment]
Hi! I'm Christina Li, you guys can call me Tina! A Monday meeting at 4:30pm works great, I'm at Roble so meeting at OU would be perfect. I have class until 4:20PM so 4:40 would be great. My number is 586-804-0935 but Facebook messenger works too!

**Comment by ggarza5** [comment]
Hi it's Gabriel I signed us up for 4:40 SGM on wednesday talk to yall tomo
